### ISSUE TITLE
Umbrella Issue: candidates bio

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/community#1060]
This issue is just a kindly reminder for folks who haven't submitted their bio :)

- [X] Aaron Crickenberger
- [X] Aaron Schlesinger
- [X] Adnan Abdulhussein
- [X] Alex Pollitt
- [X] Caleb Miles
- [X] Derek Carr
- [X] Doug Davis
- [X] Ihor Dvoretskyi
- [X] Ilya Dmitrichenko
- [X] Jaice Singer DuMars
- [X] Justin Santa Barbara
- [X] Kris Nova
- [X] Matt Farina
- [X] Michael Rubin
- [X] Michelle Noorali
- [X] Phillip Wittrock
- [x] Quinton Hoole
- [X] Rob Hirschfeld
- [X] Sebastien Goasguen
- [X] Timothy St. Clair

~~ref: https://github.com/kubernetes/community/pull/1058 (Make bio files follow name convention)~~

/cc @castrojo

**Comment by quinton-hoole** [comment]
I added my bio.  https://github.com/kubernetes/community/pull/1101

**Comment by xiangpengzhao** [comment]
Thanks @quinton-hoole!

@kris-nova the vote is already started, can you finish your bio when you get a chance? :)

**Comment by xiangpengzhao** [comment]
All done.
/close
