### ISSUE TITLE
Mentoring Umbrella Issue

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#1672]
We have a brand new home in the community repo for mentoring docs. We've kicked off testing for all three strategies listed on the [README](https://github.com/kubernetes/community/tree/master/mentoring). These tackle various learning styles, audiences, and our needs of continuous contributor growth. 

This is a task list of where we need help, engagement, and/or your opinions. I'll add the corresponding issues/docs to each once they are set; they will have more detail and context. 

- [ ] [Outreachy](outreachy.org)
* Need more sponsoring organizations, SIGs, and mentors. $6500/per intern. 
* Google and CNCF picked up the sponsorship this semester for the two CLI folks we have. CNCF will sponsor one intern per semester.

- [ ] Group Mentoring: 
* Need SIGs/WGs interest in mentoring for a certain ladder level (made up example: SIG Networking needs more approvers)
* Need areas of growth / skills for each ladder level. See the [mentee guide](https://github.com/kubernetes/community/blob/master/mentoring/group-mentee-guide.md) for development areas and comment there. This will shape our workshops and future of Kubernetes learning and development. 
  * What does a new member need to know to be successful? 
  * What skills do reviewers need? Approvers? 
See also: #1514 - scroll for comment about "code reviews the k8s way"

- [ ] #1753 & Doc -[Meet Our Contributors](https://github.com/kubernetes/community/blob/master/mentoring/meet-our-contributors.md)
* Need volunteers to [sign up](https://goo.gl/uhEJ33). Our next session is Feb 7th at 730am PST (no volunteers needed) and 1pm PST (needed). 
* 30 min AMA style like user office hours and the last half dedicated to a live peer code review. 

- [ ] [Google Summer of Code](https://github.com/kubernetes/community/blob/master/mentoring/google-summer-of-code.md)
* Need mentors, projects, et al.

/sig contributor-experience
/assign

**Comment by parispittman** [comment]
All of these items were completed. See https://git.k8s.io/community/mentoring.

Starting a new umbrella issue to cover the latest work.

/close
