### ISSUE TITLE
Umbrella issue for Community Maintenance tasks

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1999]
This is a list of things we should audit, see https://github.com/kubernetes/community/blob/master/sig-contributor-experience/community-maintenance.md for more details.

Feel free to assign yourself to a section

### Slack
Assignee: @parispittman

- [x] Channels - Anything out of place or not following the guidelines? 
  - [x] Close unused channels. 
  - [x] Check to see if there is a purpose, pinned documents like agendas, and other best practices being used in the channel. These are not required but are useful.
- [x] Audit the Integrations and apps
- [x] Audit the user tokens
- [x] Audit the Emojis
- [x] Generate a Slack data report to share with the community (optional)

### GitHub

- [x] Audit Org admin permissions
- [ ] Audit Integrations
- [x] Check Label usage (education, deprecation, etc)
- [x] Is the PR and/or issue message still good/the best?
- [x] Check kubernetes/community/.github/PULL_REQUEST_TEMPLATE
- [x] Where’s the issue template located? 

### Calendars
Assignee: @castrojo

- [x] Check that the calendar works
  - Go to http://k8s.io/community and follow the flow
- [ ] Make sure all SIG, WG, and other community meetings are showing - especially check new groups that were created in the last quarter
- [ ] Make sure that invites have more than one owner, shared with the mailing list distro, and have an agenda attached plus zoom URL and telephone dial information.

### SIGS

- [x] Ensure everyone in `sigs.yaml` is subscribed to sigs-leads mailing list
- [x] Ensure that chairs and leads are accurate in the `sigs.yaml`

### YouTube
Assignee: @castrojo

- [x] Check sharing on all the playlists
  - Should only be shared with leads or people appointed by leads
  - Either remove other people or regenerate a new collaboration URL
- [x] Check admin permissions on the Kubernetes account
- [x] Fix any videos accidentally tagged as unlisted 
- [x] Generate a YouTube traffic report to share with the community (optional)

### Zoom

- [x] Ensure leads have access to their upgraded Zoom account
- [x] If appropriate change the password if a SIG has changed leadership 
  - Contact CNCF to adjust upgraded licenses if necessary
- [ ] Audit kubernetes.io GSuite - this is primarily needed to create associated resources like GoogleGroups and the Google Cloud organization.  Accounts in  this domain cost the CNCF actual money, so are not available for individuals. Three steering committee members will hold the keys to three accounts on the domain, which can be used to create `@kubernetes.io` groups as needed.
  - Volunteers (Ask for new representatives from the steering committee if election turnover affects this list):
    - Joe Beda (@jbeda)
    - Brendan Burns (@brendandburns)
    - Tim Hockin (@thockin)

### Community Meeting

- [x] Generate an archive of the [communtiy meeting notes](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#heading=h.2gp5yf2snwg5) for the quarter if necessary
  - [ ] Ensure the retrospective section has links to the retrospective for the releases
  - [x] Ensure the demo section is filled out and demos are assigned dates
  - [x] Ensure the [agenda template and hosting guide](https://docs.google.com/document/d/1g7fR5cvCGFq15SJ4iQMclbj0QIeREKu_QP8ftnSaJ4o/edit) are up to date 
- [x] Ensure the [SIG Schedule](https://docs.google.com/spreadsheets/d/1adztrJ05mQ_cjatYSnvyiy85KjuI6-GuXsRsP-T2R3k/edit#gid=1543199895) have SIGs assigned for the next few months
  - [x] Ensure the assigned SIGs in this sheet match the actual SIGs in sigs.yaml. Double check that a SIG hasn't missed an update this past cycle and if they have schedule them for an upcoming meeting

/sig contributor-experience

**Comment by bgrant0607** [comment]
And mailing list moderation, if that lands in contrib X.

I can't right now, but ping me next week, and I'll add more things to these lists.

**Comment by castrojo** [comment]
@bgrant0607 #2028 is the issue for moderating the lists, I'll be working on that, feel free to add more here in the comments and I'll integrate it into the master template.

**Comment by bgrant0607** [comment]
We should re-evaluate whether these teams and googlegroup mirrors are useful or even work:
https://github.com/kubernetes/community/blob/master/sig-governance.md#creating-service-accounts-for-the-sig

**Comment by tpepper** [comment]
The "Calendars" section needs updating now that the calendar is not on http://k8s.io/community

**Comment by idvoretskyi** [comment]
@castrojo since this one is called as H1'2018, shouldn't it be renamed as we are coming closely to the end of H2'2018 :)

**Comment by nikhita** [comment]
> @castrojo since this one is called as H1'2018, shouldn't it be renamed as we are coming closely to the end of H2'2018 :)

+1

Also, I think we have achieved a few of these already \o/

**Comment by cblecker** [comment]
Maybe this should just be a general "lets do these all at least once" kind of audit, and then we can figure out how to make it regular haha

**Comment by idvoretskyi** [comment]
> Maybe this should just be a general "lets do these all at least once" kind of audit, and then we can figure out how to make it regular haha

+1

**Comment by nikhita** [comment]
Should this be renamed to "Umbrella issue for Community Maintenance tasks"? :)

**Comment by idvoretskyi** [comment]
> Should this be renamed to "Umbrella issue for Community Maintenance tasks"? :)

👍

**Comment by nikhita** [comment]
Renamed.

**Comment by castrojo** [comment]
/close

Kicking off a new one for the year: https://github.com/kubernetes/community/issues/3717
