### ISSUE TITLE
Umbrella issue to sunset SIG Cluster Ops

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2031]
We actually don't have a process documented for how to turn a SIG into a WG, I suspect it's just a bunch of renaming, but filing this in github so that we can gleam info and write it down. 

Also not sure if Cluster Ops wants to move into the On Prem WG, or roll up under SIG Cluster Lifecycle. 

https://github.com/kubernetes/community/issues/2029

/cc @zehicle 
/sig cluster-ops

**Comment by spiffxp** [comment]
From a github label perspective we can either migrate sig/cluster-ops to sig/cluster-lifecycle or get rid of it. Let me know what you decide.

**Comment by jdumars** [comment]
AFAIK there should be no problem migrating existing labels to cluster-lifecycle. The other question is best answered by @zehicle

**Comment by cblecker** [comment]
Nope, totally possible to migrate. We just need to understand what should migrate where.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/committee steering
/priority important-soon
I went looking through the meeting notes and I couldn't find a written decision to truly sunset this SIG.  It just sorta tapered off.  We either need a decision on this instance, or a policy on how to treat these sorts of things going forward.

**Comment by zehicle** [comment]
Aaron,

We could not establish a consistent quorum - the group is effectively
sunset.  Let me know what actions I should take to make that official.

Sorry for the slow response.

Rob

<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Fwww.rackn.com%2F&si=5660451956457472&pi=b5476891-75f5-465d-8650-7da909995352>

Rob Hirschfeld

Co-Founder and Chief Executive Officer, RackN

(512) 773-7522

<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Ftwitter.com%2Fzehicle%3Flang%3Den&si=5660451956457472&pi=b5476891-75f5-465d-8650-7da909995352>
<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Frhirschfeld%2F&si=5660451956457472&pi=b5476891-75f5-465d-8650-7da909995352>

**Comment by parispittman** [comment]
@spiffxp Jorge and I can document the logistics/archival process if steering can take the decision on how, why, policy end. 

re: #2029

**Comment by timothysc** [comment]
Did someone delete the zoom account?  For better or worse it was shared with @kubernetes/sig-cluster-lifecycle since before I was involved.  

/cc @roberthbailey @kris-nova @detiber

**Comment by zehicle** [comment]
Lifecycle effectively owns it and uses it a lot.  Sharing was never a
problem.  Please don't delete without consulting them!

<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Fwww.rackn.com%2F&si=5660451956457472&pi=c22f965d-f4fb-4e55-a1f0-f872d00cd1af>

Rob Hirschfeld

Co-Founder and Chief Executive Officer, RackN

(512) 773-7522

<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Ftwitter.com%2Fzehicle%3Flang%3Den&si=5660451956457472&pi=c22f965d-f4fb-4e55-a1f0-f872d00cd1af>
<http://t.sidekickopen10.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2bjgW64zKpj3LyR22W1qMCsg56dVpDf9jJGjx02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Frhirschfeld%2F&si=5660451956457472&pi=c22f965d-f4fb-4e55-a1f0-f872d00cd1af>

**Comment by timothysc** [comment]
xref - https://github.com/kubernetes/community/issues/2536

**Comment by parispittman** [comment]
I'm going to create a cluster lifecycle zoom account and have cluster-lifecycle-leads@ as the username. 

@roberthbailey @timothysc @kris-nova @detiber

**Comment by zehicle** [comment]
+1

**Comment by roberthbailey** [comment]
The sig-cluster-lifecycle-leads email list has been created.

**Comment by spiffxp** [comment]
@jorge @parispittman re: https://github.com/kubernetes/community/issues/2031#issuecomment-417956179

can we follow the process that was merged in https://github.com/kubernetes/community/pull/2832 to officially sunset SIG cluster-ops?

**Comment by zehicle** [comment]
+1

<https://www.rackn.com/>

Rob Hirschfeld

Co-Founder and Chief Executive Officer, RackN

(512) 773-7522

<https://twitter.com/zehicle?lang=en>
<https://www.linkedin.com/in/rhirschfeld/>

**Comment by parispittman** [comment]
@zehicle @spiffxp - we will start on this asap post KubeCon

**Comment by zehicle** [comment]
No rush from my end

**Comment by castrojo** [comment]
This is the current status: 

- [x] SIG Chairs agree to disband. This decision should follow the decision making process of the SIG's Charter.
- [x] Send a email to kubernetes-dev to let people know the SIG has either closed or merged with another SIG. This will let SIG Contributor Experience know that they need to help you archive/deactivate project resources.
- [ ] Archive the mailing list/group
- [ ] Archive the leads mailing list/group
- [x] Archive the slack channel
- [x] Deactivate the group's Zoom license
- [x]  Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
- [x] Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
- [x] File an issue with kubernetes/org if multiple repos that need to be retired
- [ ] Retire or transfer any test-infra jobs owned by the SIG
- [ ] Retire or transfer any testgrid dashboards owned by the SIG
- [ ] Clean up and remove all GitHub teams that refer to that SIG/WG
- [ ] Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
- [x] Ensure that the YouTube Collaboration links are removed
- [x] Remove SIG Calendar and events from the community calendar
- [x] Update sigs.yaml to reflect the removal of the SIG/WG

The mailing list/google group predate our group governance process, so I don't have the permission to archive them, hoping either @idvoretskyi or @sarahnovotny have access to this. 

/cc @kubernetes/sig-testing on the jobs if any
/cc @kubernetes/test-infra-admins for the labels

**Comment by BenTheElder** [comment]
Checking in from sig-testing: AFAIK there are not any jobs. Searching testgrid seems to confirm.

**Comment by cblecker** [comment]
`Clean up and remove all GitHub teams that refer to that SIG/WG`

Can confirm none exist.

**Comment by zehicle** [comment]
I turned the google group to read only.
I was not able to change the grouppleads rights.

**Comment by castrojo** [comment]
Alright, both lists set to read-only and not allowing new members. Thanks everyone.
