### ISSUE TITLE
Umbrella Issue for Mentoring Programs Enhancements

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2663]
This issue will capture other smaller issues and the larger picture for the current state + work to do in the 7 mentoring programs that we have.

General Mentoring
- [x] update README with the latest information
- [ ] do a mentor recruiting campaign (after most of the programs are near a state of full launch)
contributor comms team can help with this one!
- [x] organize the data on mentors and mentees better
- [ ] create a github process (applying to be a mentor and a mentee) instead of a google form
- [x] rework the mentoring folder so that it's organized as /mentoring/programs, /mentoring/processes which may help with some of the automation ideas that are floating around

the 1:1 hour
- [x] update README with the latest information
- [ ] addressed concerns in issue: #2657 

group mentoring
- [x] update README with the latest information
- [ ] addressed concerns in these issues: #2659, #3479 

meet our contributors
- [x] update README with the latest information
- [ ]  #3481

**Comment by nikhita** [comment]
Since this is an umbrella issue, maybe this should be removed from the milestone...?

**Comment by nzoueidi** [comment]
I am going to dig into this in the few upcoming days.

**Comment by markyjackson-taulia** [comment]
/assign markyjackson-taulia
Adding myself also as an assignee

**Comment by markyjackson-taulia** [comment]
Initial meeting took place today and the notes are here: https://docs.google.com/document/d/1WESip6l2r1sOQwIiKWV9aAUhQtqH1DDrnuTvwz0RXJ0/edit?userstoinvite=laura.santamaria@logdna.com&ts=5e18a07b&actionButton=1#

A recurring weekly meeting have been scheduled for every Friday 8 am pst to 8:30 am pst.

Action items are reflected in the notes and will be updated either via new issue or adding to an existing issue.

cc @parispittman @chris-short

**Comment by chris-short** [comment]
Did we want or already have a Slack channel?

**Comment by parispittman** [comment]
pls use contribex. we've tried this already and folks use that channel to find mentors and then its more triage than planning.

**Comment by parispittman** [comment]
yay more things checked off

**Comment by markyjackson-taulia** [comment]
@jberkus This item will be a shared issue for group and 1:1 mentoring

**Comment by markyjackson-taulia** [comment]
For issue #2657, the mentoring 1:1, I have proposed a flow
