### ISSUE TITLE
Expand moderation groups umbrella issue

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3128]
This is not a call for recruitment right now.

Issue:

- [ ] update docs on moderation experience and/or contributor experience requirements to prepare for said call for recruitment
    - [ ] platforms that need more moderators: slack, youtube, zoom, googlegroups (need to check on discuss.k8s)
- [ ] re-review all docs for updated information on moderation expectations and actions on all platforms
- [x] send proposal to steering for google group on the @kubernetes.io account for moderators@kubernetes.io to bring all of our moderators under one umbrella contact for disseminating information rapidly regarding the health of the community, updated policies and procedures, etc. [note: sent on Feb 6th wrapped into the gsuite proposal/documentation/email thread]

**Comment by parispittman** [comment]
this should be a priority this week 

need to add incident response guidelines and processes

**Comment by parispittman** [comment]
/help

help from other admins here please

**Comment by parispittman** [comment]
sent ask for moderators@kubernetes.io to the steering committee mailing list today - pending response

**Comment by nikhita** [comment]
Is this done? We've had an overhaul of our moderation docs afaik. :)

/cc @castrojo @mrbobbytables @jeefy

**Comment by mrbobbytables** [comment]
I think so \o/

**Comment by nikhita** [comment]
> I think so \o/

Cool! Closing this. Please reopen if needed.

/close
