### ISSUE TITLE
Umbrella issue - API conventions, changes, review guidelines

### ISSUE THREAD

**Issue by liggitt** [kubernetes/community#3211]
This issue is to coordinate efforts to improve and add to the [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md) and [API changes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md) documentation, based on existing issues files and feedback from reviewers/shadows.

Questions encountered during designs/reviews (answer or clarify in existing docs):
- ...

Issues encountered during code reviews (add guidance to relevant docs, or make more explicit if it already exists):
- [ ] don't increment storage version of a resource in the same release that introduces the new version (breaks HA upgrade)

Checklists for reviewing different types of API changes:
- [ ] New API group
- [ ] New resource
- [ ] New version of an existing resource
- [ ] New field in an existing resource (some guidance exists in [API changes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md) doc, ensure it is up to date)
- [ ] New allowed value in an enum field
- [ ] New value in a union type
- [ ] Tightening validation
- [ ] Relaxing validation

see also:
- [ ] PUT creating objects - https://github.com/kubernetes/community/issues/876
- [ ] name length limit - https://github.com/kubernetes/community/issues/814
- [ ] use of finalizers  - https://github.com/kubernetes/community/issues/691
- [ ] conventions for RAW API fields - https://github.com/kubernetes/community/issues/357
- [ ] list of api_changes suggestions - https://github.com/kubernetes/community/issues/1297
- [ ] overall developer guide improvements - https://github.com/kubernetes/community/issues/3064

**Comment by liggitt** [comment]
@kubernetes/sig-architecture-api-reviews @kubernetes/sig-api-machinery-api-reviews

**Comment by liggitt** [comment]
cc @kubernetes/api-approvers @kubernetes/api-reviewers 
/assign

**Comment by liggitt** [comment]
[Pod priority and preemption review](https://docs.google.com/document/d/1W3nqRejktMXFR3ykmDBMJOCPt3EvpAMh11NF72N_AqI/edit#)

**Comment by liggitt** [comment]
[Promote RunAsGroup to beta](https://docs.google.com/document/d/1sA-XVWOimfov1Gemw02Bwi50bGazeRc3hod0JL4wA_0/edit) review notes

**Comment by thockin** [comment]
CSINodeInfo and CSIDriver notes: https://docs.google.com/document/d/1pkCYjr_OLCRUk2e606eMa2PEIwJdFHAfU5slXtBcKj8/edit#

**Comment by thockin** [comment]
CSI Inline Volumes: https://docs.google.com/document/d/19-q0YR6D1wuZwrdBl3U5Xp9Wg6d7UXPFXKvKv5uH96w/edit#heading=h.8i4r99zg796y

**Comment by thockin** [comment]
Ingress -> network group:  https://docs.google.com/document/d/1RycD0x-WUBvPjtTyLYCZF_db_Jv9b36NW1PynMEOm9Q/edit

**Comment by liggitt** [comment]
[PSP RuntimeClass review](https://docs.google.com/document/d/1iewP5AAzgNLfuT776apDnpPQGVziEc5cD457piYc36s/edit#heading=h.lc03g1lvldxg)

**Comment by liggitt** [comment]
[volume expansion secret review](https://docs.google.com/document/d/1Jp_8RAagO2wkRyU5dRHxdmRRibHIxGCQC8lPFKDLruk/edit)

**Comment by liggitt** [comment]
[windows GMSA review](https://docs.google.com/document/d/17n3-YxVpvpm46o8cCSGYBUszPyLOcxFAmjArJncZvgk/edit#)

**Comment by liggitt** [comment]
[inline CSI migration review](https://docs.google.com/document/d/16_Eq_ehfZEkt5DzH9zdKr7IL26E67Pjxs0Lv5OWFj3c/edit)

**Comment by nzoueidi** [comment]
I can help with this!

**Comment by vishakhanihore** [comment]
@liggitt Would you like some help here ?

**Comment by liggitt** [comment]
[HPA container-based scaling review](https://docs.google.com/document/d/1v7UeADuMt8I7CX7APmleOE1reHb9Rm9vCVIqA4J2hXk/edit) - https://github.com/kubernetes/kubernetes/pull/90691
