### ISSUE TITLE
[TRACKING] Update slides for NCW with more recent info

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#3348]
This is a tracking issue for the 2019 New Contributor Workshop content.

Please update and report any content updates that are necessary by commenting here and creating a check box for each task

- [x] We have a chart we can use for the SIG tour [here](https://github.com/kubernetes/community/blob/master/SIG-diagram.png), it was updated, and we should definitely use that as the visual for explaining SIG structure and layout.

- [x] There are specific communications via SIGs vs working groups vs Subprojects that now have an finalized shape and we should communicate those. @parispittman where can we find a doc on this?

/sig contributor-experience
/area contributor-summit
/cc @jberkus @idealhack 

- [ ] Add mention of CoC committee
- [ ] Add non-code contributor materials

**Comment by ameukam** [comment]
I don't know if this is relevant but we now have [User Groups](https://github.com/kubernetes/community/commit/44c77b522097fd069a6669fa08b81ec9ebf5e836) and [User Group gouvernance](https://github.com/kubernetes/community/pull/3620/) is still in review.

**Comment by tpepper** [comment]
We should add two or so slides around architecture of a cluster and how that relates to code in k/k (and other repos), eg:

# top level picture of control plane + worker nodes, names of binaries that run on each, lines showing how they talk to each other
# map those binary names and communication flows to associated sources

**Comment by guineveresaenger** [comment]
Hi friends, I have started re-vamping the slides for Barcelona, focusing on the morning session combined content: 
- copied Seattle slides and put them in a new deck here: 
- updated content where applicable
- added TODOs where necessary
- the intent is to use these slides more as a textbook so it is easy for participants to follow links on their own computers

Specific action items from others:
- would appreciate some artwork for top slide @jonasrosland - could you coordinate?
- @tpepper to coordinate differing content for 201 and 101 - may choose to go full blown live demo, I was thinking of keeping some topics on slides for reference but doing a lot of interactive things
- need to have potential tutors on board and enter their info - @ameukam et al

**Comment by ameukam** [comment]
Can we add  in the slides : 
- a mention of the Code of Conduct Committee
- two or three slides about the Non-code contributions roles ?

**Comment by parispittman** [comment]
event is over. we can open a new slides issue for the next event if there are other changes that need to happen post our retro. 

/close
