### ISSUE TITLE
Set milestones and groom contribex project board

### ISSUE THREAD

**Issue by nikhita** [kubernetes/community#3443]
To better plan and track the work we are doing in sig contribex and empower more people to take on and own tasks, we should add milestones and assign people (sometimes new folks and mentor them) to the issues that are actively being worked on/would be nice to have being worked on. This will also help us in prioritizing and providing direction to our work.

SIG Cluster Lifecycle has a doc on how they do this, we could start here: https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/grooming.md. I was totally blown away by how @timothysc conducted the latest Public Steering Committee meeting ([recording](https://www.youtube.com/watch?v=X3ySJ09clgQ)) using this method and I think it would be neat to incorporate something like this for our SIG as well. :)

These are the action items I see right now, feel free add suggestions too!

- [x] We go through the [project board](https://github.com/orgs/kubernetes/projects/1) in our weekly meetings. Instead, we should break this down into boards per subproject (see https://github.com/kubernetes/community/issues/3283). We can keep the main board for things that are more cross-subproject.
- [x] Make sure almost all issues have a `kind/`, `area/` and `priority/` label. 
- [x]  Create a milestone with a reasonable due date (sometime in May before KubeCon Barcelona?)
- [x] Maybe create a team `community-milestone-maintainers` to make sure this team can use the `/milestone` command. There are many folks/subproject owners who are active in contribex, but don't necessarily have write access to the repo. They should be able to add milestones too.
- [x] Add milestones to issues that seem like a good candidate for May.

Reserve one of our weekly meetings to discuss and groom the project board:

- [x] Plan and discuss which issues should stay and which ones can be removed from the current milestone (mainly look for issues that are high priority-wise and can be reasonable done by the due date).

- [x] Assign people to work on each of the issues. If an issue isn't too critical and can be done by new-ish contributors, we should use `help wanted` and `good first issue` labels and offer mentorship for them.

Finally when this is done, in our regular weekly meetings, we can walk through the issues in this milestone instead of the whole project board. We could probably let subproject owners just give us a quick update on the issues, instead of going through each one too. 

/sig contributor-experience
/assign @nikhita @parispittman @Phillels

**Comment by nikhita** [comment]
I just want to add this for completely clarity: these milestones are a nice-to-have and are to help us prioritize our work. These are **not meant to be deadlines**!

This is an open source project, most of us are stretched thin already and are working on this on our personal time. If we don't get an issue done by a milestone due date, that's **completely okay**! We can always bump it to the next milestone and/or try looking at alternatives like mentoring others to take up sub-tasks, etc.

If you are assigned to an issue that has a milestone and feel like you won't be able to work on it within the milestone date, feel free to comment about it. Prioritizing self care is more important than prioritizing issues. :heart:

**Comment by parispittman** [comment]
thanks for this nikhita! 

subproject boards have been created - let me know if you see one missing

ps - if you're reading this, we are looking for a project manager! :D

**Comment by spiffxp** [comment]
@nikhita @parispittman would it be helpful to have project board for the github-management subproject?  I'm not sure how often its issues come up in contribex these days

AFAIK we want to keep track of
- [`repo:kubernetes/community label:area/github-management`](https://github.com/kubernetes/community/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aarea%2Fgithub-management+) issues
- [`repo:kubernetes/org -label:area/github-membership`](https://github.com/kubernetes/org/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Aarea%2Fgithub-membership) issues
- [`repo:kubernetes/test-infra label:area/prow/peribolos`](https://github.com/kubernetes/test-infra/labels/area%2Fprow%2Fperibolos) issues and PRs

I can volunteer (post-1.14) to help consistently apply the `area/github-management` label to all three of these repos and work with the team to prioritize if we feel there's value there.

**Comment by parispittman** [comment]
definitely will be helpful and happy to create. we can always delete if necessary. 

for those following along, an update:
k8s.io
devstats
repo-infra 

will not have their own project boards, they are small groups and can be handled at the main meeting. if activity kicks up that would warrant, then we can propose tracking them in this fashion.

**Comment by nikhita** [comment]
> @nikhita @parispittman would it be helpful to have project board for the github-management subproject? 

Yes! I'll create it today. :)

**Comment by nikhita** [comment]
Created a project board for github-management: https://github.com/orgs/kubernetes/projects/25

kubernetes/community-admins@, kubernetes/community-maintainers@ and kubernetes/owners@ have write access. All org members have read access and it is visible to the Public.

**Comment by mrbobbytables** [comment]
/milestone May
:)

**Comment by nikhita** [comment]
Notified sig-contribex ML: https://groups.google.com/d/topic/kubernetes-sig-contribex/KneETB-_NAc/discussion

**Comment by nikhita** [comment]
We have the following project boards right now:

- Main Contribex board - https://github.com/orgs/kubernetes/projects/1
- github-management - https://github.com/orgs/kubernetes/projects/25
- community-management - https://github.com/orgs/kubernetes/projects/24
- mentoring - https://github.com/orgs/kubernetes/projects/18
- Contributor summits:
    - EU - https://github.com/orgs/kubernetes/projects/19
    - CN - https://github.com/orgs/kubernetes/projects/20
    - NA - https://github.com/orgs/kubernetes/projects/21

I went through most issues and added them to the relevant project boards + if they were added to a subprojects' board, removed them from the main contribex board.

I have also added milestones to issues that felt like a good candidate for targeting for the May milestone.

**Comment by idvoretskyi** [comment]
@nikhita great, thanks for doing this!

**Comment by nikhita** [comment]
This is done!!! :tada: :tada: :tada:

Thank you soooo much for the hard work with triaging and applying milestones, everyone! :smile: 

/close
