### ISSUE TITLE
[Umbrella Issue] NA Contributor Summit Registration

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#3837]
Umbrella for smaller issues related to NA summit registration. Further tasks TBD.

- [x] Gather additional questions for registration (primarily NCW information)
- [x] Create and test sample separate registration flows for NCW and Current Contributors.
- [x] Create seperate registration pages for NCW and Current Contributors.
- [x] Determine Phased registration dates and groups. (ref #3866)
- [ ] Roll out phased registration.

/sig contributor-experience
/area contributor-summit
/area na-summit

**Comment by guineveresaenger** [comment]
For NCW, the absolutely necessary questions/prompts:

- What is your GitHub handle?
- Please sign the CLA (and be aware this may involve your company's Legal department, so make sure to do it well in advance of the workshop. If you don't sign, you may not be able to participate in exercises
- Please bring in a Macbook or a Linux VM setup (unless we have Windows figured out by then)

Optional:

- Which area of Kubernetes are you interested in contributing? Topics may include: api, cli, test-infra, networking, docs, community, release, etc
- Are there any SIGs you may want to join (if you don't know what a SIG is, that's ok!)

To decide which course to take:

- Beginner: (title TBD) general dev environment setup, github workflow, finding your first issue, how to be a good opensource citizen, assumes little or no prior Kubernetes experience
- Intermediate: (title TBD) k/k codebase walkthrough, building, testing, assumes your dev environment is set up and you have some Kubernetes experience

There will be shared content: org/repo overview, SIG organization, and the Meet-and-Greet.

**Comment by alisondy** [comment]
following up from what @jberkus mentioned in the NCW google doc, Having some questions to gauge what session would be best for participants would be good.

It could also backfire though, by making wrong impression on who is registering. We don't want people to feel like they're not experienced enough to make a start. I might be overthinking it though. 

A few sample questions below
> Have you submitted a PR to Kubernetes before? 
> How familiar are you with go?
> Tick the following you have setup on the machine you will be bringing along : Docker, Go

**Comment by raelga** [comment]
About the mandatory question:

* Please sign the CLA (and be aware this may involve your company's Legal department, so make sure to do it well in advance of the workshop. If you don't sign, you may not be able to participate in exercises

Maybe we can also encourage the folks to ask in Slack if they are having issues settings things up for the contributor summit before the event. 

* Please bring in a Macbook or a Linux VM setup (unless we have Windows figured out by then)

And don't forget the charger, is always good to point it out.

Optional:

* Are you in the Kubernetes Slack?
* What is your Slack handler (if applies)?

Maybe increasing the visibility of the #contributors-summit channel before the event can help provide an easy way for the attendees to get in touch with other attendees. And also, be used as a communication channel to provide support if any attendee has any issue or question with the Contributors Summit.

* Which language you feel more comfortable with?

Just to check if it may be useful to provide more examples for non-golang contributions.
 
* What do expect to get from the event?

To know a bit more about what the folks coming to the event expect to learn during the event. That can provide some information prior to the event.

**Comment by parispittman** [comment]
need key dates

**Comment by parispittman** [comment]
question for current contributor reg:
- what sig(s) are you most active in? list no more than two/three

will assist in content changes/additions, sig meet-and-greet, and discussion track(s)

**Comment by jberkus** [comment]
> following up from what @jberkus mentioned in the NCW google doc, Having some questions to gauge what session would be best for participants would be good.

Following up on this:

For CS Shanghai, we had a decision tree for registrants, so that we funneled them to the appropriate type of registration.  It seemed to work fairly well.  We can do the same for San Diego; the tricky part is the questions to separate 101 from 201.

Note that for us Doc Sprints were also part of the CS registration.  Are they in SD?

**Comment by guineveresaenger** [comment]
re: key dates - When does overall conference registration usually close/sell out? I'd recommend closing about 2 weeks after this event occurs.

**Comment by parispittman** [comment]
target 7/22 for prototype; 7/29 for build on site

**Comment by parispittman** [comment]
update: 7/29 for prototype

**Comment by parispittman** [comment]
https://docs.google.com/spreadsheets/d/1KFpRE5U2TOW7lecBShowSPUS-Bad-mIJjE_WsqxMm1g/edit#gid=0 - reg questions from bob
