### ISSUE TITLE
Contributor Summit SD: Unconference Umbrella Tracker

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/community#3894]
Umbrella issue collecting the following:

  - [x] Sync with @castrojo for Seattle unconf knowledge transfer
  - [x] Walk through venue (Owner): @markyjackson-taulia
  - [x] Start [documentation](https://docs.google.com/document/d/1oZF8ZYzpVbickinDXyKyWk1WdhTkVBEP5FHdcdIJnvw/edit#) (Owner): @markyjackson-taulia
  - [x] Breakdown task (Owner): @markyjackson-taulia & @thecrudge 
  - [x] Create PR with added information in to community/events-team/content/unconference.md (#4024)
  - [x] Get materials list together and determine ordering (In progress)
* Markers
* Index cards
* Rolling whiteboard
* Pens
- [x] Do overall walk through with @thecrudge (this was done on 11/10 at 6pm pst via zoom)
- [x] Update content md with notes for the unconference (https://github.com/kubernetes/community/pull/4229)
- [x] Add template for note taking (https://github.com/kubernetes/community/pull/4229)
- [x] Ship whiteboard to my name address 333 W. Harbor San Diego, CA. 92101. This will go to the UPS store located inside the hotel which has instructions to hold for me. This was verified today 11/10. Shipping will take place on Tuesday 11/12 and will arrive Thursday 11/14

**Comment by parispittman** [comment]
@castrojo can you link up with @markyjackson-taulia and discuss what you did for the unconf in seattle?

**Comment by markyjackson-taulia** [comment]
Jorge is on vacation till the 22nd. I did send an email to start the conversation when he return and is settled from vacation

**Comment by markyjackson-taulia** [comment]
Meeting with Jorge today at 1:30 PM PST

**Comment by markyjackson-taulia** [comment]
Met with @castrojo (love him!). I will start the documentation once the walk through is completed on Wed..

**Comment by markyjackson-taulia** [comment]
Walk through completed and I will now start the documentation process

**Comment by markyjackson-taulia** [comment]
Documentation completion ETA Monday 7/29

**Comment by markyjackson-taulia** [comment]
*Update*
- [x] Get @thecrudge synced on the items already completed and what is to come
- [] Start the task list (in progress)
- [] Create rolebook/best practices for unconferences and then PR that into community repo (in progress

**Comment by jeefy** [comment]
I think the Rolebook checkbox can be completed. ;)

@markyjackson-taulia Do you mind updating the root issue description with the current task list? It's difficult at a glance to see the status of things when they're lower in the comments :( Looks like things are cruising along though, thanks!

**Comment by markyjackson-taulia** [comment]
I would like to do a walk over of the plan @thecrudge either this week or early next week. This is our final rulebook checkbox before showtime.

**Comment by markyjackson-taulia** [comment]
The above walk through was completed this evening with @thecrudge and some pr's were noted above

**Comment by markyjackson-taulia** [comment]
This has been completed so closing.

**Comment by markyjackson-taulia** [comment]
Start of the unconference notes are here https://github.com/kubernetes/community/tree/master/events/2019/11-contributor-summit/unconference-notes

I also need to add some retro documentation to the notes here: https://github.com/kubernetes/community/blob/master/events/events-team/content/unconference.md

**Comment by markyjackson-taulia** [comment]
@thecrudge Link to this issue and I *HUGELY* nominate you as lead for the unconference Amsterdam if the opportunity presents itself.
cc: @jeefy
