### ISSUE TITLE
doc: code of conduct committee off/onboarding checklist

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3954]
need a checklist of access, perms, docs needed for new code of conduct committee members

known:

- [ ] mailing list (conduct@)
- [ ] slack channel - members will have to remove themselves during offboarding; a cocc member will need to add new folks
- [ ] beacon perms - we have access to the beacon prototype; will need to share info
- [ ] meeting agenda - perms are through conduct@ 
- [ ] sigs.yaml - need to figure out if the new members PR or someone on the cocc team does
- [ ] past cases, issues, etc. and those in the process at that time

also need to think about when this stuff happens. do we give auto rights to these things on the day the acceptance comes through or when we have an onboarding / welcome meeting?

**Comment by parispittman** [comment]
confirming jennifer and eric have been removed from conduct@

**Comment by parispittman** [comment]
added aeva and tasha to mailing list and slack channel

**Comment by parispittman** [comment]
sent email to new committee which included a doodle for our first meeting (sometime between sept 6th - 11th), link to this issue, and some welcome notes.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

cc @karenhchu @celestehorgan @tpepper

**Comment by celestehorgan** [comment]
/assign

I'll write this all down 😌
