### ISSUE TITLE
Contributor Summit SD: CNCF Planning Umbrella Issue

### ISSUE THREAD

**Issue by debgiles** [kubernetes/community#3970]
An umbrella issue to cover the different areas that CNCF is working on intersecting with the ContribEx Team.

**GENERAL INFO**
KC+CNC Schedule Announcement - September 5

**VENUE LOGISTICS**
- [x] Space Requirements Deadline
- [x] Space Confirmed
- [x] Schedule site visit between CNCF + Summit Lead (if needed)
- [x] Share walkthrough video of space (https://drive.google.com/file/d/1Hl-yysWGKJsNV8Eanq5T36VB_uuvTOqP/view?usp=sharing)
- [x] Provide meeting space grid with room requirements in planning doc (Meeting Space + AV Grid tab - https://docs.google.com/spreadsheets/d/1vBbuAT7IZ6lOaPOkbZlEejGULfqAnpOl1BwYxxKxDO8/edit#gid=1207731845)
- [x] Room layouts and AV requirements finalized - September 16
- [x] Schedule onsite venue walk-through the day prior to event

**EVENING CELEBRATION**
- [x] Requirements deadline
- [x] Venue finalized
- [x] Info added to website
- [x] Bingo Card Questions (#3914) for Design Deadline - October 18 
- [x] Bingo Card for Printing Deadline (#3914) (If ContribEx designing them) - November 1

**REGISTRATION**
- [x] Registration form framework doc shared (https://docs.google.com/spreadsheets/d/1KFpRE5U2TOW7lecBShowSPUS-Bad-mIJjE_WsqxMm1g/edit#gid=0)
- [x] Finalize registration launch timeline
- [x] Registration form framework deadline
- [x] Registration form for testing
- [x] Registration form live - September 4

**ATTENDEE COMMUNICATIONS**
- [x] Attendee Comms framework doc shared (https://docs.google.com/document/d/1EIpaFmrqp3qqXsnGhpr4H-RoFeFSd4dHZJ6M8RwyHBI/edit)
- [x] Finalize attendee communications timeline
- [x] Registration Open email copy deadline - August 26
- [x] Pre-Event Know Before You Go email copy deadline - November 7
- [x] Post-Event New Contributor copy deadline - November 19
- [x] Post-Event Current Contributor copy deadline - November 19

**WEBSITE**
- [x] Save the Date website live
- [x] Website framework doc shared (https://docs.google.com/document/d/1mulfto6GpXogbQYmAoY9EGh5NOsfXUopRylivMdIcFg/edit)
- [x] Finalize website launch timeline
- [x] Added to KC+CNC Co-located page
- [x] Website framework deadline - August 23
- [x] Website launch - September 4

**CONTENT**
- [x] Sched created (https://kcsna2019.sched.com/)
- [x] Create event powerpoint template (#
- [x] AV requirements confirmed - September 16
- [x] Sched built out and added to website - October 1

**SWAG**
- [x] Determine how to distribute patches - handout onsite or provide a code to order
- [x] T-Shirt artwork deadline - October 11

**SIGNAGE (PRINT + DIGITAL)**
- [x] Signage request deadline - September 25
- [x] Signage examples shared - October 14
- [x] Print deadline - October 15
- [x] Digital signage request deadline - October 28

**Comment by hpandeycodeit** [comment]
The issue to track Bingo cards for Event celebration: #3914

**Comment by hpandeycodeit** [comment]
Issue for tracking Sunday Night Celebration/Evening Celebration: #3893

**Comment by mrbobbytables** [comment]
All items checked and complete \o/

Going to go ahead and close this out. 

Thanks!

/close
