### ISSUE TITLE
Contributor Summit EU 2020: CNCF Planning Umbrella Issue

### ISSUE THREAD

**Issue by debgiles** [kubernetes/community#3995]
An umbrella issue to cover the different areas that CNCF is working on intersecting with the ContribEx Team.

**GENERAL INFO**
KC+CNC Schedule Announcement - January 22

**VENUE LOGISTICS**
- [x] Space Requirements Deadline - August 31
- [x] Space Confirmed - January 2020
- [x] Schedule site visit between CNCF + Summit Lead (if needed) - January 2020 - NOT NEEDED
- [x] Share walkthrough video of space - January 2020 - Unavailable
- [x] Provide meeting space grid with room requirements in planning doc - January 17
- [x] Room layouts and AV requirements finalized - February 7
- [x] Schedule onsite venue walk-through the day prior to event - February 24

**EVENING CELEBRATION**
- [x] Requirements deadline
- [x] Venue finalized - January 2020
- [x] Info added to website - January 2020

**REGISTRATION**
- [x] Registration form framework doc shared - December 9
- [x] Finalize registration launch timeline - December 9
- [x] Registration form framework deadline - January 13
- [x] Registration form for testing - January 20
- [x] Registration form live - January 27

**ATTENDEE COMMUNICATIONS**
- [x] Attendee Comms framework doc shared - December 9
- [x] Finalize attendee communications timeline - December 9
- [x] Registration Open email copy deadline - January 20
- [ ] Pre-Event Know Before You Go email copy deadline - March 18
- [ ] Post-Event New Contributor copy deadline - March 23
- [ ] Post-Event Current Contributor copy deadline - March 23

**WEBSITE**
- [x] Save the Date website live - November 2019
- [x] Website framework doc shared - December 9
- [x] Finalize website launch timeline - December 9
- [x] Added to KC+CNC Co-located page - January 27
- [x] Website framework deadline - January 13
- [x] Website launch - January 27

**CONTENT**
- [X] Sched created - January 2020 (https://kcseu2020.sched.com/)
- [x] Create event powerpoint template - January 2020 (https://drive.google.com/open?id=1TJSn4qTvipUYe_anP6MrlU5vViSZ5CGY)
- [x] AV requirements confirmed - February 7
- [x] Sched built out and added to website - February 7

**SWAG**
- [x] T-Shirt artwork deadline - February 7

**SIGNAGE (PRINT + DIGITAL)**
- [x] Signage request deadline - February 10
- [ ] Signage examples shared - February 17
- [ ] Print deadline - February 21
- [ ] Digital signage request deadline - March 9

**Comment by mrbobbytables** [comment]
With the cancellation of the EU summit, I'm going to go ahead and close out the remaining open issues. If you think something should still be addressed. Please go ahead and reopen 👍 

/close
