### ISSUE TITLE
[Umbrella] Contributor Summit Amsterdam Current Content

### ISSUE THREAD

**Issue by idealhack** [kubernetes/community#4406]
Opening this to track the tasks of Content for current contributors at the Amsterdam event.

- [x] form the team with two shadows
- [x] create a CFP form (https://forms.gle/eMHu6WsAj8RG9aC36)
- [x] send out CFP open notice (https://groups.google.com/forum/#!topic/kubernetes-dev/D7pHcT-FxWA)
- [x] close the CFP
- [x] review proposals
- [x] shedule a program
- [x] reach out to speakers
- [x] confirm the schedule and put on sched
- [ ] on-site operations

/sig contributor-experience
/area contributor-summit
/area eu-summit

/assign

**Comment by mrbobbytables** [comment]
You have now been added as an admin to sched, the URL for the Amsterdam summit is:
https://kcseu2020.sched.com

**Comment by idealhack** [comment]
@mrbobbytables thanks!

**Comment by idealhack** [comment]
/assign @puja108 @onlydole 
for on-site operations

**Comment by onlydole** [comment]
Hello team! I will not be on-site for Amsterdam (unfortunately), but I will be able to help with anything you need, otherwise!

**Comment by mrbobbytables** [comment]
With the cancellation of the EU summit, I'm going to go ahead and close out the remaining open issues. If you think something should still be addressed. Please go ahead and reopen 👍 

/close
