### ISSUE TITLE
[umbrella] contributor twitter account bootstrap

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4516]
- [x] set up guidelines
- [x] research collaboration tools
- [x] send out a short list vote on handles to k-dev@ mailing list / #4554

**Comment by spiffxp** [comment]
We are ok with the use of this twitter account so long as we are explicit about how it's used re:KEPS

**Comment by spiffxp** [comment]
PR to review: https://github.com/kubernetes/community/pull/4729

**Comment by mbbroberg** [comment]
This one is done. We're moving on into implementation phase.

**Comment by parispittman** [comment]
Closing this - we are done here
