### ISSUE TITLE
SIG PM Retirement tracking issue

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#4721]
Following the [announcement of SIG PM's retirement](https://groups.google.com/d/topic/kubernetes-dev/RU8iINF758Y/discussion), there's some associated administrivia to complete the process.

I'll get the ball rolling and use this issue to track work.

- [x] Send an email to kubernetes-dev@googlegroups.com and community@kubernetes.io alerting the community of your intentions to disband or merge. [example]
  - Retirement announcement: https://groups.google.com/d/topic/kubernetes-dev/RU8iINF758Y/discussion)
- [x] Archive the member and lead/chair mailing lists/[GoogleGroups]
  - The member list has been archived, but the [leads list](https://groups.google.com/forum/#!members/kubernetes-pm-leads) cannot be as @sarahnovotny's Google account is the only owner on it.
- [x] Check the [slack-guidelines.md] for latest process on archiving the slack channel
  - [x] (https://github.com/kubernetes/community/pull/4722) Rename `#sig-pm` to `#enhancements`
- [x] Deactivate the zoom license
  - I believe this was already done a while back by @mrbobbytables or @castrojo
- [x] Delete your shared SIG/WG/UG calendar
- [x] Ensure that the [youtube-guidelines.md] links are removed and you've uploaded all SIG/WG/UG meetings to date
- [x] (https://github.com/kubernetes/community/pull/4722) Move the existing SIG directory into the archive in `kubernetes/community`
- [x] GitHub archiving/removing/other transactions:
  - [x] (https://github.com/kubernetes/enhancements/pull/1685) Move all appropriate github repositories to an appropriate archive or a repo outside of the Kubernetes org
  - [x] (https://github.com/kubernetes/enhancements/pull/1685) Each subproject a SIG owns must transfer ownership to a new SIG, outside the project, or be retired
  - [x] ~File an issue with kubernetes/org if there are multiple repos~ N/A
  - [x] (https://github.com/kubernetes/test-infra/pull/17227) Retire or transfer any test-infra jobs or testgrid dashboards, if applicable, owned by the SIG. Work with SIG Testing on this.
  - [x] Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml
    - [x] (https://github.com/kubernetes/test-infra/pull/17221) Set deletion for `sig/pm` and add `area/enhancements` label
    - [x] Manually relabel relevant `sig/pm` issues/PRs to `area/enhancements`
    - [x] (https://github.com/kubernetes/test-infra/pull/17229) Delete `sig/pm` label spec after 4/20/20
  - [x] (https://github.com/kubernetes/org/pull/1796) Remove or rename any GitHub teams that refer to the SIG
- [x] (https://github.com/kubernetes/community/pull/4722) Update sigs.yaml to remove or rename

/sig architecture
/assign @justaugustus @mrbobbytables @castrojo
cc: @jeremyrickard @johnbelamaric

[example]: https://docs.google.com/document/d/1qZcAvuWBznR_oEaPWtwm7U4JNT91m8r9YOUvInU-src/edit#heading=h.jsw0l2t0ra8
[GoogleGroups]: https://git.k8s.io/community/communication/mailing-list-guidelines.md
[slack-guidelines.md]: https://git.k8s.io/community/communication/slack-guidelines.md
[youtube-guidelines.md]: https://git.k8s.io/community/communication/youtube/youtube-guidelines.md

**Comment by justaugustus** [comment]
I think we're all set here, but feel free to open follow-up issues as needed.
/close
