### ISSUE TITLE
2020 Steering Committee Election Tracking

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#5019]
- [x] Generate voters.md
- [x] obtain emails and create email queue
- [x] Create 2020 intial election documents
- [x] Create exemption form
- [x] Send election announcement to kdev and start accepting nominations
- [x] Send weekly nomination status updates to kdev
- [x] Send notifications that nominations close in 24 hours
- [x] Hold Steering/candidates public session
- [x] Prep ballot
- [x] Send out CIVS ballots
- [x] Send weekly election status updates
- [x] Send 24-hour notice on voting
- [x] Collate results
- [x] Announce results at public steering committee meeting
- [x] Publish post-election blog
- [x] Election retro

/area community-management
/committee steering
/sig contributor-experience

/assign jdumars
/assign idvoretskyi
/assign

**Comment by mrbobbytables** [comment]
With the election completed, and retro held this should be good to close :)

Thanks everyone!

/close
