### ISSUE TITLE
[Tracking Issue] 2020 Contributor Survey

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5153]
This is the general tracking issue for the 2020 survey
ref: https://github.com/kubernetes/community/issues/4464

- [x] [Review 2019 Survey Question](https://docs.google.com/document/d/1IERzLwPBJkw5IYnolJ0UnS3ueWNEhePpoeRtTzIlrqs/edit)
- [x] [Call for changes to ContribEx ML by November 13th](https://groups.google.com/d/msg/kubernetes-sig-contribex/UZNz2gUtxrE/N-ojeLONBAAJ)
- [x] [Finalize Survey questions](https://docs.google.com/document/d/1IERzLwPBJkw5IYnolJ0UnS3ueWNEhePpoeRtTzIlrqs/edit?usp=sharing)
- [x] Build survey in surveymonkey
- [x] Engage with Marketing team to plan announcement (DO NOT advertise on kubernetesio twitter)
   - send to all email lists
   - use k8scontributors account
- [ ] Analyze results / Write follow-up blog post
- [x] Codify the process of requesting surveys 

/sig contributor-experience
/area community-management
/milestone v1.20

**Comment by jberkus** [comment]
Step 0 is going to be deciding who's the lead on the Survey this year.  Anyone want to run it?

**Comment by jberkus** [comment]
Also, at this point, maybe we call it the 2021 survey?

**Comment by mbbroberg** [comment]
I'm aiming to get someone assigned to help with communications on Friday, Jan 15.

**Comment by mrbobbytables** [comment]
Just to update, Survey has been sent out - It is targeted to close on the 21st

**Comment by jberkus** [comment]
/remove-lifecycle stale

we still need to publish a report on this

**Comment by mrbobbytables** [comment]
TBH, it's been so long since we conducted the survey I don't think it'd make much of a difference if it was posted this year =/ Maybe roll the report into next year?

**Comment by jberkus** [comment]
@mrbobbytables +1.  The results of the survey were pretty boring from what I could see anyway.

**Comment by mrbobbytables** [comment]
kk, we'll go ahead and close this out 👍 
/close
