### ISSUE TITLE
[Tracking Issue] Virtual Contributor Celebration 2020

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5242]
**Goal**
Create and host an event for Kubernetes contributors to regain some of the missed social and networking with in-person events. 

**Context**
Contributors are very much feeling virtual-event burnout and miss the "hallway" track of regular events. Polling the leads has shown very little interest in pre-recorded presentations, but a desire for more interactive and fun events.

- Social fun (games, movies etc)
- Workshops
- Hackathons

Of those the emphasis was **very much on social**. Workshops and Hackathons can be encouraged if people are interested, but the focus of the event should be on avenues for folks to have fun and network.

**Date**

Date for the event is TBD. There was no clear winner from the survey. It also does not have to directly align with KubeCon.

**Next steps**

- Recruit summit team.
- Spin back up the weekly summit meeting.
- Solicit ideas for platform and activities.

---

/area contributor-summit
/sig contributor-experience
/milestone v1.20

**Comment by mrbobbytables** [comment]
/assign @mrbobbytables @castrojo @jeefy 
to kick things off

**Comment by markyjackson-taulia** [comment]
I would love to help in any way possible!

**Comment by jeefy** [comment]
Organize games? Online? lol I think I can help here. 

ACK and sign me up, I've got a few ideas

**Comment by palnabarun** [comment]
Count me in for any help required. :)

Would love to help again with the summit. 🙌🏽

**Comment by cpanato** [comment]
i would like to help as well in any way, making virtual coffee or anything :)

**Comment by eddiezane** [comment]
Echoing my comments from sig-contribex call.

It would be great if we can find a way to incorporate "meet the sigs" in someway. 2019 San Diego's session was where I managed to find a home in the community. Target audience could potentially be more for New Contributor Workshop folks though.

**Comment by castrojo** [comment]
I reached out to Matt Stratton who hosts "DevOps Party Games", which is a You-Don't-Know-Jack style game. 

- https://devopspartygames.com/
- https://www.youtube.com/watch?v=Cji-wxJjUoA&list=PLpIuPh9QbvVLyn55QAr9_C1UHrjKYPDng&index=4

This probably wouldn't be able to scale to have everyone being able to participate, but if we can get the right mix of people running the games it could be fun for everyone else to watch along and chat along in twitch, etc.

**Comment by thecrudge** [comment]
Me too would love to help out as always :) Super exciting.

**Comment by castrojo** [comment]
Here is the schedule page: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/schedule/

How does the evening after the first day vibe with everyone? I'm thinking people will be dead tired if we do it at the end.

**Comment by thecrudge** [comment]
Tuesday?

**Comment by mrbobbytables** [comment]
We are not bound to it being tied to kubecon as well.

**Comment by Pensu** [comment]
Would love to help out in any way possible. Count me in  :)

**Comment by aravindputrevu** [comment]
Happy to help in any way possible!

**Comment by mrbobbytables** [comment]
A thought regarding timing - what are folks thoughts on potentially hosting it after the 1.20 release (December 8th)? If the focus is social, that should be the last real big "deadline" for the year.

**Comment by jeefy** [comment]
I +1 a more "EOY" type event. Make it more of a celebration as well.

**Comment by jeefy** [comment]
Just to get some of it out of my head

- Online games (Destiny, Among Us) and Trivia, each "lobby" hosted by someone who can handle / report on any potential COC issues.
- Have a "featured game" that we stream (on Twitch. Maybe use CNCF's Twitch?) and seed with people we know are fun and entertaining
- Bring in different podcasters and have them do "live versions" of their shows for this event
- Host our own award show. Some voted on, some not. Largest PR. Most Comments. Most Slack messages. Most engagement in Stack Overflow.
- Do some practical unboxings of new features that landed this year

The goal here is: We provide inclusive/fun/relevant programming to everyone in our community who wants to watch/stay connected but can't/won't participate. But also provide activities for those that want to, relax (or sweat, depending on the game) with friends.

I want us to err on the side of "fun" rather than "professional"

**Comment by alisondy** [comment]
I would love to help out! 👋

**Comment by munnerz** [comment]
I'd also like to help out! 😄 +1 on something social focused.

**Comment by alisondy** [comment]
+1 for end of year

**Comment by markyjackson-taulia** [comment]
+1 to having this after the 1.20 release

**Comment by parispittman** [comment]
big +1 to post kubecon.

**Comment by youngnick** [comment]
+1 to having this after the 1.20 release, looking forward to staying up to see everyone!

**Comment by mrbobbytables** [comment]
As we've had enough +1 for post kubecon/release - I'm thinking 10th/11th->13th. Essentially Thursday/Friday through the weekend. As it will mostly be just keeping a discord up and going, we should be able to support it through the weekend with minimal overhead.

**Comment by mrbobbytables** [comment]
[Discord](https://discord.com/) is looking to be the ideal platform for this, for its robust AV and moderation capabilities. The best bot I've found is [yagpdb](https://yagpdb.xyz/). It's OSS, verification system supports an external captcha that covers the various accessibility needs.

Some additional items that need to be hammered out.
- [x] Provision discord server
- [ ] Configure Bot
    - [ ] captcha verification/role configured
    - [ ] CoC linked with sign off before being added to main group
    - [ ] template out channel layouts/roles for activities
- [ ] convert discord server to community server (welcome page + other reqs)
-  [ ] help wrangle team for mod duties (slack admins anyone with discord experience would be good)
- [ ] event page on k8s.dev
- [ ] update k/community/events with current status
-  [ ] comms regarding the event
   - [ ] solicit feedback for additional games (google form etc)
-  [ ] Identify other activities (web based, no real OS game requirements - trivia)

**Comment by mrbobbytables** [comment]
FYI - looking for help on any of the above^^

**Comment by alisondy** [comment]
@mrbobbytables i can help put together questions for a survey regarding what activities and games folks would be interested in

**Comment by jeefy** [comment]
Doodle poll for planning meeting: https://doodle.com/poll/5sxgtp6q7zpfdbwe

Time boxed to EOD Friday PT.

**Comment by mrbobbytables** [comment]
[Planning Doc](https://docs.google.com/document/d/15xsaoy0VeX0Z7-908Hm4ojVheHxXZB2MavNzQWgDcL0/edit)- Please refer to the planning doc for **up-to-date information.**

Before the meeting tomorrow, please review the open questions and either add answers/questions to the doc or add your thoughts in the open threads in #summit-staff slack channel.

---
**Timeline**
- Week of 11/9
  - Form for game/activity suggestions
  - Registration Form
  - Site: Event page with brief description of events on k8s.dev
  - Comms message with info, game form, reg form - to be sent by Friday
  - Ping slack admins for moderation assistance
- Week of 11/16 (KubeCon week)
  - Bump Discord server to tier 3
  - Switch Discord to community mode
- Week of 11/23 (US Thanksgiving week)
- Week of 11/30
  - Any scheduled events posted
  - FAQ Completed and updated on site / discord
  - Moderator Faq completed and posted to mod-faq channel
  - Walkthrough instructions on joining discord
- Week of 12/7 (1.20 release / event week)
  - All channels stubbed
  - Emojis synced

---
**Links:**
- [Planning Doc](https://docs.google.com/document/d/15xsaoy0VeX0Z7-908Hm4ojVheHxXZB2MavNzQWgDcL0/edit)
- [Attendee FAQ](https://docs.google.com/document/d/13oVv5f4YZwDyp7aGfLdVUlPp7lxxeMPfpahwvmreFN4/edit)
- [Moderator FAQ](https://docs.google.com/document/d/1hLuReX9a6zaRkp0lFWvypXzZju_1iahJZ52YKMyVWRU/edit)
- [Activity Info](https://docs.google.com/document/d/15xsaoy0VeX0Z7-908Hm4ojVheHxXZB2MavNzQWgDcL0/edit)

**Comment by mrbobbytables** [comment]
Smaller break down of help wanted tasks are being called out in the `#summit-staff` channel.

**Comment by jeefy** [comment]
This should get updated with the survey/feedback piece and then closed out once we get it all.

**Comment by mrbobbytables** [comment]
Yup, we'll close it out on Wednesday after the retro

**Comment by mrbobbytables** [comment]
awards have been sent out and started to be received. I plan to go ahead and close this out, the remaining awards creation in k/community will be created as a separate issue.

/close
