### ISSUE TITLE
Contributor Summit NA 2021: CNCF Planning Umbrella Issue

### ISSUE THREAD

**Issue by debgiles** [kubernetes/community#5823]
An umbrella issue to cover the different areas that CNCF is working on intersecting with the ContribEx Team.

**GENERAL INFO**
KC+CNC Schedule Announcement - August 4, 2021

**VENUE LOGISTICS**
 - [x] Space Requirements Deadline - June 1
 - [x] Space Confirmed
 - [x] Schedule site visit between CNCF + Summit Lead (if needed) - Deb will complete the site visit on July 7 and provide a walkthrough video of the space for the Summit Team
 - [x] Share walkthrough video of space - https://drive.google.com/file/d/1PdfQhPQQjrGQEDSxwuhqWtmX8ZTsHydp/view?usp=sharing
 - [x] Provide meeting space grid with room requirements in planning doc (Agenda tab - https://docs.google.com/spreadsheets/d/1TLmn4-w_nnAo5aWY-yalJj0hjGl5gLloeO2iRk8g-0E/edit#gid=928138801)
  - [x] Initial Room layouts and AV requirements - July 16
  - [x] Room layouts and AV requirements finalized - August 16
  - [x] Will the Harbor Box be needed onsite again - No
  - [ ] Schedule onsite venue walk-through the day prior to event

**EVENING CELEBRATION**
 - [x] Requirements deadline
 - [ ] Venue finalized
 - [ ] Info added to website
 - [ ]  Bingo Card Questions for Design Deadline - September 17

**REGISTRATION**
  - [x] Registration form framework doc shared (https://docs.google.com/document/d/1LmE1R9EpAJGHlWebabwijvIzdT7uW8-q9eAW0lvtDCI/edit?usp=sharing)
  - [x] Finalize registration launch timeline
  - [x] [Registration form framework deadline](https://docs.google.com/document/d/1LmE1R9EpAJGHlWebabwijvIzdT7uW8-q9eAW0lvtDCI/edit) - 2 weeks before launch - July 19
  - [x] Registration form for testing - 1 week before launch - July 26
  - [x] Registration form live - August 2 (KubeCon schedule announced August 4)
 
**ATTENDEE COMMUNICATIONS**
  - [x] Attendee Comms framework doc shared (https://docs.google.com/document/d/1pWjGK5ncoC_A2dsjE_Lb6GcXV8Z8yWkjeV7WFMPTwxk/edit?usp=sharing)
  - [x] Finalize attendee communications timeline
  - [x] Registration Open email copy deadline - 1 week before launch - July 26
  - [ ] Pre-Event Know Before You Go email copy deadline - September 30
 - [ ]  Post-Event Current Contributor copy deadline - October 5

**WEBSITE**
 Managed by ContribEx on Kubernetes site

**CONTENT**
  - [x] Sched created (https://kcsna2021.sched.com/ - Let Deb know if you need admin access)
  - [x] Create event powerpoint template - [Linked here](https://drive.google.com/file/d/1HZjCcOju-UfKocKEHShkM_-goyL1LoHi/view?usp=sharing)
  - [x] AV requirements confirmed - August 16
  - [ ] Sched built out and added to website

**SWAG**
  - [x] Determine how to distribute patches - handout onsite or provide a code to order
  - [ ] T-Shirt artwork deadline - August 20

**SIGNAGE (PRINT + DIGITAL)**
  - [x] Signage request deadline - August 6
  - [ ] Signage examples shared - August 18
  - [ ] Print deadline - September 1
  - [ ] Digital signage request deadline - September 17

**Comment by jeefy** [comment]
![image](https://i.imgur.com/vwMin.gif)

**Comment by jberkus** [comment]
Deb: current plan is that I'll do a shirt design based on some LA landmark; expect a draft in the first week of August.  However, if Tim has a stroke of inspiration before then, he'll take over.

**Comment by debgiles** [comment]
Sounds good @jberkus!

**Comment by mrbobbytables** [comment]
/close

The summit is over
