### ISSUE TITLE
Kubernetes Third-Party Security Audit for 2021 (tracking issue)

### ISSUE THREAD

**Issue by reylejano** [kubernetes/community#5875]
Tracking issue for the Kubernetes third-party security audit for 2021:
- [X] Create RFP
  - [X] Audit scope
  - [X] Finalize dates: RFP opening and closing dates, question period, vendor selection
  - [X] Complete question period and publish questions & replies to RFP 
- [ ] Vendor assessment
  - [ ] Assemble vendor assessment group
  - [ ] Create private Slack channel
  - [ ] Create private Google group
- [ ] Release vendor selection
- [ ] Publish findings

/sig security
/label external-audit

**Comment by reylejano** [comment]
I agree to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on [CVE communications](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) and have no conflict of interest

**Comment by jlk** [comment]
I agree to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on [CVE communications](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) and have no conflict of interest

**Comment by sunstonesecure-robert** [comment]
I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications and have no conflict of interest - just in the interest of FULL 200% transparency I do often speak with, and employ, various pentesting companies. I have hired previously unrelated to CNCF projects 1 of the vendors, and have spoken to all of them at some point in the past 12 months, but no active or pending business/contracts/conflicts at this moment.

**Comment by aasmall** [comment]
I agree to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on [CVE communications](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) and have no conflict of interest

**Comment by PurelyApplied** [comment]
I agree to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on [CVE communications](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) and have no conflict of interest.

----

> The label(s) `/label external-audit` cannot be applied.

There was a `wg/security-audit` working group label, but it was folded into the `sig/security` label in #5120.

**Comment by raesene** [comment]
I agree to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on [CVE communications](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) and have no conflict of interest. In the interests of full transparency, I am an ex employee of a pentesting company, and as a result know various people in the industry, however I am not currently employed in that industry.
