### ISSUE TITLE
[Umbrella] Security Assessment Process for Kubernetes sub-projects

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/community#5921]
**Goal**: Define, execute and improve on a community driven security assessment process for kubernetes sub-projects, which is self-service and welcomes beginners without prior security background to engage and contribute

## Background

CNCF TAG Security has a well established [process](https://github.com/cncf/tag-security/tree/main/assessments) for project maintainers to engage them in a security review process. However, typically the scope is limited to CNCF projects _not_ sub-projects of graduated projects like Kubernetes. In case of Kubernetes, SIG Security is taking up this responsibility to work within the project community through self-assessments as a partnership between maintainers and SIG Security Members

## Scope

- [X] Identify first project as a pilot for this process (Cluster API)
- [X] Create a draft template for self-assessment and gather feedback ([Self-Assessment Template](https://docs.google.com/document/d/1urwOa0lhzbA2XsFyDZrg2x5Fg_yEHCzSu740FDhn_go/edit))
- [ ] Publish draft template after incorporating feedback, in markdown under `kubernetes/community/sig-security`
- [ ] Publish a task list that covers the entire security assessment process (channel creation, identifying contributors, presenting and resolving findings, etc.)
- [ ] Create a Github Issue Template to allow anyone to request a security assessment for a sub-project
- [ ] Perform retrospective on the process and identify improvements after every assessment

## Related Issues

Cluster API pilot discussion: https://github.com/cncf/tag-security/issues/603 
Cluster API tracker: https://github.com/kubernetes/community/issues/5814
Admission controller: https://github.com/cncf/tag-security/issues/731

/assign @PushkarJ
cc @rficcaglia @reylejano @savitharaghunathan @kubernetes/sig-security-leads 
/sig security
