### ISSUE TITLE
2021 Steering Committee Election Tracking

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#6125]
- [x] Generate voters.md
- [x] obtain emails and create email queue
- [x] Create 2021 initial election documents
- [x] Create Elekto election configuration
- [x] Send election announcement to kdev and start accepting nominations
- [x] Send weekly nomination status updates to kdev
- [x] Send notifications that nominations close in 24 hours
- [x] Merge all candidate profiles
- [x] Schedule old Steering and candidate session(s)
- [x] Announce start of election
- [x] Send weekly election status updates
- [x] Send 24-hour notice on voting
- [x] Collate results
- [x] Announce results at public steering committee meeting
- [x] Publish post-election blog
- [ ] Election retro

/area community-management
/committee steering
/area elections
/sig contributor-experience

/assign coderanger
/assign alisondy
/assign

**Comment by mrbobbytables** [comment]
@jberkus @coderanger @alisondy think this can be closed? We did hold the retro; there are a few follow up items on for the next SC meeting, but I think thats it.

**Comment by jberkus** [comment]
I still need to upload the ballots, and then I'll close.

**Comment by jberkus** [comment]
Uploaded.

/close
