### ISSUE TITLE
Kubernetes Contributor Summit NA 2022 - CNCF Umbrella Issue

### ISSUE THREAD

**Issue by debgiles** [kubernetes/community#6733]
### Describe the issue

An umbrella issue to cover the different areas that CNCF is working on intersecting with the ContribEx Team.

**GENERAL INFO**
KC+CNC Schedule Announcement - August 3

**VENUE LOGISTICS**
- [x]  Space Requirements Deadline - April 18
- [x]  Space Confirmed - July 2022
- [x]  Share walkthrough video of space - July 2022 (https://drive.google.com/drive/folders/1hK0BwJ32WeCQ4BEj0ox3cvSH7CzgQY4m)
- [x]  Provide meeting space grid with room requirements in [planning doc](https://docs.google.com/spreadsheets/d/1Y1tqyHSUpMJb3o1ghUzbT40SPCFY3BXBeTYd8O4c_6U/edit#gid=0)
- [x]  Room layouts and AV requirements finalized - August 29
- [ ]  Schedule onsite venue walk-through the day prior to event - September 23

**EVENING CELEBRATION**
- [x]  Requirements deadline - July 2022
- [ ]  Venue finalized - August 2022
- [ ]  Info added to website - September 2022

**REGISTRATION**
- [x]  [Registration form framework doc](https://docs.google.com/document/d/1qxCv87sajUoO-kj2dQYAOxrcITRPqRjH3TdDMpZOewI/edit?usp_dm=true) shared
- [x]  Finalize registration launch timeline - July 2022
- [x]  Registration form framework deadline - Friday, July 22
- [x]  Registration form for testing - Friday, July 29
- [x]  Registration form live - Monday, August 1

**ATTENDEE COMMUNICATIONS**
- [x]  Attendee Comms framework doc shared
- [x]  Finalize attendee communications timeline
- [ ]  Pre-Event Know Before You Go email copy deadline - October 10
- [ ]  Post-Event email copy deadline - October 25

**CONTENT**
- [x]  [Sched](https://kcsna2022.sched.com/) created
- [x]  Create [event powerpoint template](https://docs.google.com/presentation/d/1Wy3PzkoVvuNKFQ1-xNEgT72S2zEgC6zw/edit#slide=id.p1)
- [x]  AV requirements confirmed - August 29
- [ ]  Sched built out and added to website - TBD

**SWAG**
- [x]  T-Shirt artwork deadline - August 29

**SIGNAGE (PRINT + DIGITAL)**
- [x]  Signage request deadline - August 29
- [ ]  Signage examples shared - September 12
- [ ]  Print deadline - September 21
- [ ]  Digital signage request deadline - October 7

**Comment by mrbobbytables** [comment]
/close
 the event is complete
