### ISSUE TITLE
Kubernetes Contributor Summit EU 2023 - CNCF Umbrella Issue

### ISSUE THREAD

**Issue by BrienneAlves** [kubernetes/community#7069]
**Describe the issue**
An umbrella issue to cover the different areas that CNCF is working on intersecting with the ContribEx Team.

**GENERAL INFO**
KC+CNC Schedule Announcement – December 2022

**VENUE LOGISTICS**

- [x] Space Requirements Deadline – January 31, 2023
- [x] Space Confirmed – February 2023
- [x] Provide meeting space grid with room requirements in [planning doc](https://docs.google.com/spreadsheets/d/1rnnTeW7uBVtS6rtDrlDkBuprG10PRzFe43BcImx6LT0/edit#gid=0)
- [x] Room layouts and AV requirements finalized – March 2023
- [ ] Schedule onsite venue walk-through the day prior to event – early April 2023

**EVENING CELEBRATION**

- [x] Requirements deadline – January 2023
- [x] Venue finalized – February 2023
- [x] Info added to website – February 2023

**REGISTRATION**

- [x] [Registration form framework doc](https://docs.google.com/document/d/14ZAkz7p0hzOp1pEs6mh05ixD2xs3jpyGmk0Qv14Dijs/edit) shared - January 2023
- [x] Finalize registration launch timeline – January 2023
- [x] Registration form framework deadline - Friday, January 27, 2023
- [x] Registration form for testing – Monday, January 30, 2023
- [x] Registration form live – Wednesday, February 1, 2023

**ATTENDEE COMMUNICATIONS**

- [x] [Attendee Comms framework doc](https://docs.google.com/document/d/1VTvU2My0jZs8f-ovOCKc-J6Qdu7nxFe2gmJy9DxbMEA/edit#heading=h.gjdgxs) shared – January 2023
- [x] Finalize attendee communications timeline – January 2023
- [x] Pre-Event Know Before You Go email copy deadline – Friday, April 7, 2023
- [ ] Post-Event email copy deadline – Wednesday, April 26, 2023

**CONTENT**

- [x] Sched created – February 2023
- [x] Create event PowerPoint template – February 2023 
- [x] AV requirements confirmed – Tuesday, March 21, 2023
- [ ] Sched built out and added to website - TBD

**SWAG**

- [x] T-Shirt artwork deadline – January 2023

**PRINT SIGNAGE**

- [x] Signage request deadline – Tuesday, March 7, 2023
- [x] Signage examples shared – Monday, March 13, 2023
- [x] Print deadline – Friday, March 17, 2023

**Comment by sarthaksarthak9** [comment]
pls assign this issue to me

**Comment by mrbobbytables** [comment]
@sarthaksarthak9 this is an umbrella tracking issue, there is nothing directly to assign.

**Comment by sarthaksarthak9** [comment]
@mrbobbytables ok
