### ISSUE TITLE
Tracking Issue for promoting for @aravindhp becoming sig-windows co-chair

### ISSUE THREAD

**Issue by marosset** [kubernetes/community#7158]
### Describe the issue

# Leadership Changes

- [x] Discuss the proposed changes with the current leadership.

- [x] Send an email to the SIG/WG/UG mailing list and cc the [kubernetes-dev]
mailing list. At a minimum, the email should contain:
  - [x] intent to step down as the current lead
  - [x] if nominating another lead
    - [x] 1-2 lines about why they are being nominated
    - [x] contacts to privately reach out to for questions (current leads)
          or concerns (current leads + [steering-private]) about the nomination
  - [x] if this was discussed in a meeting, link to meeting notes
  - [x] lazy consensus deadline of at least one week

- [x] If nominating another lead, ensure that they
  - [x] are a Kubernetes GitHub org [member]
  - [ ] have completed the [Inclusive Open Source Community Orientation course]

- [x] Once lazy consensus has been achieved, update the following
      files in the respective repos:
  - [x] [kubernetes/community]: [`sigs.yaml`] and use the [generator doc]
        to update `README.md` and `OWNERS_ALIASES` files
  - [x] [kubernetes/org]: `OWNERS_ALIASES`, [milestone-maintainers team],
        kubernetes and kubernetes-sigs [team configs]
  - [x] [kubernetes/enhancements]: `OWNERS_ALIASES`
  - [x] [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io): `groups/groups.yaml` - leads email group members

- [x] Update all communication properties used by the community group.
      See [sig-wg-lifecycle.md] for details.

Note: If multiple candidates are running for an open lead position and
lazy consensus cannot be achieved, an election should be held.
SIG Contributor Experience should be contacted to assist with the
administration of the election.

[kubernetes-dev]: https://groups.google.com/a/kubernetes.io/g/dev
[steering-private]: steering-private@kubernetes.io
[member]: /community-membership.md#member
[`sigs.yaml`]: /sigs.yaml
[generator doc]: /generator
[kubernetes/community]: https://github.com/kubernetes/community
[kubernetes/org]: https://github.com/kubernetes/org
[kubernetes/enhancements]: https://github.com/kubernetes/enhancements
[milestone-maintainers team]: https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml
[team configs]: https://git.k8s.io/org/config
[Inclusive Open Source Community Orientation course]: https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/
[sig-wg-lifecycle.md]: /sig-wg-lifecycle.md

**Comment by marosset** [comment]
Announcement mail sent to mailing lists - https://groups.google.com/g/kubernetes-sig-windows/c/jFLFUAQpM2c/m/Z8HEIeN9AQAJ

**Comment by marosset** [comment]
cc @jsturtevant @jayunit100 @claudiubelu @aravindhp

**Comment by aravindhp** [comment]
Here is the proof of completing the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/): https://www.credly.com/badges/0cacba06-dce6-4f86-8f7c-e57bcfbee8b9/public_url

**Comment by marosset** [comment]
/close
Everything in the checklist is done
Thanks again and welcome @aravindhp!!
