### ISSUE TITLE
Group Mentoring - Program Updates and Enhancements

### ISSUE THREAD

**Issue by xcarolan** [kubernetes/community#8008]
This issue will be the parent issue of tasks required for Group Mentoring Planning.

- [ ] Update mentoring landing page  #8021
- [ ] Update the mentoring guide for the group cohorts  #8010 https://github.com/kubernetes/community/blob/master/mentoring/programs/group-mentoring.md](url)
- [ ]  Reach out to SIGs to gauge interest #8009 
- [ ] determine mentee audience (beginners, existing contributors, reviewers etc.) 
- [ ] Set timeline and cadence
- [ ]  set up or reinitiate the mentoring sub-project
- [ ]  update project material if needed

/sig contributor-experience
/area mentorship-planning
